version: "3.8"
name: nest-thermostat-exporter
networks:
  back-tier:
    name: internet-monitoring-back-tier
    external: true
services:
  nest-exporter:
    restart: always
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    expose:
      - 8000
    ports:
      - '8000:8000'
    volumes:
    - ./app:/app
    environment:
      - DATABASE=/app/sqlite.db
    env_file:
      - .env
    # networks:
    #   - back-tier